spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST}:5432/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    hikari:
      max-lifetime: 300000
      keepalive-time: 120000
      connection-timeout: 10000
      validation-timeout: 5000

server:
  address: '::'
  forward-headers-strategy: framework

investlog:
  demo-mode:
    enabled: true

  security:
    totp:
      enabled: false
